export { default as http, get, post, put, deleteMethod, form } from './utils/http';
export { usePrevious, useCompare, useDifferentiation } from './utils/hooks';
export { default as history } from './utils/history';
export { default as getAPI } from './utils/services/getAPI';
export { default as getDifferentiation } from './utils/getDifferentiation';
export { default as replacePlaceholder } from './utils/replacePlaceholder';
export { default as loadScripts } from './utils/loadScripts';
export { default as loadStyles } from './utils/loadStyles';
export { default as stringToDomElement } from './utils/stringToDomElement';
export { default as classnames } from './utils/classnames';
